# Generated by Django 5.0.3 on 2024-06-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_admin', '0003_adminmovies'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmovies',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
        migrations.AddField(
            model_name='adminmovies',
            name='video_file',
            field=models.FileField(default=11, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
