# Generated by Django 5.0.3 on 2024-06-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_admin', '0004_adminmovies_subtitle_file_adminmovies_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmovies',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='adminmovies',
            name='video_file',
            field=models.FileField(upload_to=''),
        ),
    ]
